on:
  repository_dispatch:
    types: [build-event]
  schedule:
    - cron: "0 0 * * *"

jobs:
    update-gist:
      runs-on: ubuntu-latest
      steps:
        - name: productive-box
          uses: maxam2017/productive-box@v1.2.0
          env:
            GH_TOKEN: ${{ secrets.GH_TOKEN }}
            GIST_ID: 3b011312f5c5b360ea3ace72888fc136
            TIMEZONE: Asia/Seoul
              
            
